/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:6aebce7f-4b6f-44f8-96ad-5eab5e3675d4",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_yvmbWUnIq",
    "aws_user_pools_web_client_id": "7dblavc2g6m629kf1ca5q5q19o",
    "oauth": {}
};


export default awsmobile;
